apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: demo
spec:
  replicas: 2
  selector: { matchLabels: { app: myapp } }
  template:
    metadata: { labels: { app: myapp } }
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: myapp
          image: 192.168.20.104:5000/myorg/myapp:latest
          ports:
            - containerPort: 5000
