apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: demo
spec:
  selector: { app: myapp }
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  type: ClusterIP
